### ISSUE TITLE
Installing the Android SDK in the Program Files directory could be problematic

### ISSUE THREAD

**Issue by dmssargent** [JacobAMason/FTCDevSuite#12]
The Android SDK in Program Files or Program Files (x86) requires elevated permissions to update and/or modify which would requires users to use special instructions to update or change components in the Android SDK.

Stack Overflow: http://stackoverflow.com/questions/4771895/android-sdk-manager-not-installing-components

A solution could be to install to `%systemdrive%\Android\SDK` or to `%public%\Android\SDK`

**Comment by JacobAMason** [comment]
I was torn between Program Files and the root after moving it from LocalAppData. My reasoning was this: I believe the population of users who wouldn't know how to elevate permissions is probably the same population that doesn't need to be modifying the API/SDK versions. But I guess it'll be okay.

**Comment by dmssargent** [comment]
My point is more of that if an important update comes along, or the FIRST SDK changes the target SDK or something like that happens, then some teams may be stuck at trying to reinstall the SDK, because the proper channels that the school gives for updating things is a few weeks minimum. 

Maybe an option to change the the SDK location for per-machine or per-user could be useful, or allowing the user to specify a custom Android SDK directory.

**Comment by JacobAMason** [comment]
Making the SDK location optional is probably more confusing. Everything else the installer does in terms of environment setup is machine-level, so I don't mind having the SDK stored in a machine-level location.

**Comment by dmssargent** [comment]
I am fine with the machine level Android SDK; my problem is more of the security restrictions imposed on the Program File directories. 

The best thing I can currently think of is when no Android SDK can be found and the user is not installing Android SDK with the installer, the installer won't automatically disable first run in the Android Studio (which give more helpful error messages, than Android Studio not going through a first run)

**Comment by JacobAMason** [comment]
I looked back at the code and remembered why I chose that location: the standalone SDK installer uses Program Files as it's "All Users" install location. I used the standalone SDK installer because it was very small and easy to pack in the Net installer. I download that installer to the user's machine, install it (it only installs the manager, no default packages), and then use a script to download only the parts of the SDK necessary. The Full installer has the entire android-sdk folder packaged and it simply moves it into the Program Files directory, setting ANDROID_HOME.

Note to self: the workaround is to stop using the standalone SDK installer. Just package the manager executable, it can't be that large. Drop it in the system drive and use the batch file.

I found that if I didn't disable first run, Android Studio tries to download the latest version of the SDK, which the project doesn't need. This is bad for venues with little bandwidth, and doesn't work well with the concept of a internet-connection-free installation.

**Comment by dmssargent** [comment]
Android Studio (in my experience) doesn't prompt to install the Android SDK if ANDROID_HOME is set, and the ANDROID_HOME points to a valid SDK. However, Android Studio can't really operate without an Android SDK and if the user doesn't have one or install one, they would have to manually install one instead of using Android Studio's SDK Manager to install it. Venues with limited internet connections should use the full installer, which installs the Android SDK internet connection free, Android Studio shouldn't have a problem with that SDK, if everything in the SDK is good.

About the SDK Manager executable, it is the dependencies that take up the space.
The minimum I can come up with is about 9.17 MB when zipped, (it requires the JDK to be installed)

I will verify the entire Android Studio first run tomorrow, both with and without an Internet connection.

**Comment by dmssargent** [comment]
It seems that if build tools 24, sources 24, Android Support repository, Google Android m2 repository are installed in the SDK, and everything is up to date the Android Studio's first run doesn't do anything, otherwise it installs and updates those packages at this time.
